language: generic
compiler:
  - clang
  - gcc
dist: trusty
sudo: required
install:
- bash Documentation/script/ros_indigo_base.sh
- sudo apt-get install -qq ros-indigo-ros-controllers
before_script:
- source /opt/ros/indigo/setup.bash
- mkdir -p ~/catkin_ws/src
- catkin_init_workspace ~/catkin_ws/src
- ln -s "$(pwd)" ~/catkin_ws/src
- cd ~/catkin_ws
script:
- catkin_make
after_success:
- source ~/catkin_ws/devel/setup.bash
